### ISSUE TITLE
Build error with 0.1.11

### ISSUE THREAD

**Issue by aghanti7** [yang-f/flutter_svg_provider#23]
```
% fvm flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0.1 21A559 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)
```

This is the error:
```
: Error: Type 'AssetBundle' not found.
../…/lib/svg.dart:325
    AssetBundle? bundle,
    ^^^^^^^^^^^
: Error: 'AssetBundle' isn't a type.
../…/lib/svg.dart:325
    AssetBundle? bundle,
    ^^^^^^^^^^^
```

Specifically with these versions:
```
flutter_svg:
    dependency: transitive
    description:
      name: flutter_svg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.23.0+1"
  flutter_svg_provider:
    dependency: "direct main"
    description:
      name: flutter_svg_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.11"
```
